#!/usr/bin/env python3

# Simple tool to generate bundle formats for kiwi image builds
# Author: Neal Gompa <ngompa@fedoraproject.org>
# SPDX-3.0-License-Identifier: GPL-3.0-or-later
# SPDX-2.0-License-Identifier: GPL-3.0+

from argparse import ArgumentParser
from pathlib import Path

import xml.etree.ElementTree as ET


parser = ArgumentParser(description="Generator of kiwi bundle formats for Fedora image builds")
parser.add_argument("kiwi_file", type=Path, default="Fedora.kiwi", help="kiwi description file")
parser.add_argument("image_profile", type=str, help="kiwi image profile")
args = parser.parse_args()

xml_tree = ET.parse(args.kiwi_file)
image_root = xml_tree.getroot()

image_basename = image_root.attrib["name"]
image_profile = args.image_profile

print(f"{image_basename}-{image_profile}-%v.%I.%A")
