[spins.lxqt.x86_64]
fas = [ "zsun", "farchord", "ngompa" ]
maintainers = [ "Zamir SUN", "Steve Cossette", "Neal Gompa" ]
[spins.lxqt.aarch64]
fas = [ "zsun", "farchord", "ngompa" ]
maintainers = [ "Zamir SUN", "Steve Cossette", "Neal Gompa" ]

[spins.xfce.x86_64]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]
[spins.xfce.aarch64]
fas = [ "nonamedotc", "kevin", "maxamillion" ]
maintainers = [ "Mukundan Ragavan", "Kevin Fenzi", "Adam Miller" ]

[kde.x86_64]
fas = [ "marcdeop", "ngompa" ]
maintainers = [ "Marc Deop", "Neal Gompa" ]
[kde.aarch64]
fas = [ "marcdeop", "ngompa" ]
maintainers = [ "Marc Deop", "Neal Gompa" ]

[spins.kde-mobile.x86_64]
fas = [ "tdawson", "ngompa" ]
maintainers = [ "Troy Dawson", "Neal Gompa" ]
[spins.kde-mobile.aarch64]
fas = [ "tdawson", "ngompa" ]
maintainers = [ "Troy Dawson", "Neal Gompa" ]

[spins.cinnamon.x86_64]
fas = [ "grinnz" ]
maintainers = [ "Dan Book" ]

[spins.cosmic.x86_64]
fas = [ "ryanabx" ]
maintainers = [ "Ryan Brue" ]

[spins.lxde.x86_64]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]
[spins.lxde.aarch64]
fas = [ "cwickert", "mtasaka" ]
maintainers = [ "Christoph Wickert", "Mamoru TASAKA" ]

[spins.mate_compiz.x86_64]
fas = [ "raveit65" ]
maintainers = [ "Wolfgang Ulbrich" ]

[spins.soas.x86_64]
fas = [ "chimosky", "aperezbios" ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez" ]
[spins.soas.aarch64]
fas = [ "chimosky", "aperezbios", ]
maintainers = [ "Chihurumnaya Ibiam", "Alex Perez" ]

[labs.astronomy_kde.x86_64]
fas = [ "lupinix", "q5sys" ]
maintainers = [ "Christian Dersch", "JT Pennington" ]

[labs.security.x86_64]
fas = [ "fab", "jsimon", "q5sys"]
maintainers = [ "Fabian Affolter", "Joerg Simon", "JT Pennington" ]

[labs.design_suite.x86_64]
fas = [ "luya" ]
maintainers = [ "Luya Tshimbalanga" ]

[labs.games.x86_64]
fas = [ "dogphilosopher", "owensz", "jaidenriordan", "lleyton", "ngompa" ]
maintainers = [ "Noel Miller", "Owen Zimmerman", "Jaiden Riordan", "Lleyton Gray", "Neal Gompa" ]

[labs.jam_kde.x86_64]
fas = [ "q5sys" ]
maintainers = [ "JT Pennington" ]

[labs.python_classroom.x86_64]
fas = [ "churchyard", "python-sig" ]
maintainers = [ "Miro Hrončok", "Python SIG" ]

[labs.scientific_kde.x86_64]
fas = [ "q5sys", "lecris", "scitech"  ]
maintainers = [ "JT Pennington", "Cristian Le", "SciTech SIG" ]
 
[labs.scientific.x86_64]
fas = [ "q5sys", "lecris", "scitech"  ]
maintainers = [ "JT Pennington", "Cristian Le", "SciTech SIG" ] 

[labs.robotics.x86_64]
fas = [ "lrossett", "robotics-sig" ]
maintainers = [ "Leonardo Rossetti", "Robotics SIG" ]

[spins.i3.x86_64]
fas = [ "jflory7", "defolos", "nasirhm", "odilhao", "x3mboy" ]
maintainers = [ "Justin Flory", "Dan Čermák", "Nasir Hussain", "Odilon Junior", "Eduard Lucena" ]

[eln]
fas = [ "sgallagh", "tdawson", "asamalik", "yselkowitz" ]
maintainers = [ "Stephen Gallagher", "Troy Dawson", "Adam Samalik", "Yaakov Selkowitz" ]

[spins.budgie.x86_64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]

[spins.sway.x86_64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]

[spins.miraclewm.x86_64]
fas = [ "mattkae", "ngompa" ]
maintainers = [ "Matthew Kosarek", "Neal Gompa" ]

[spins.phosh.x86_64]
fas = [ "lihis", "phosh-sig" ]
maintainers = [ "Tomi Lähteenmäki", "phosh-sig" ]
[spins.phosh.aarch64]
fas = [ "lihis", "phosh-sig" ]
maintainers = [ "Tomi Lähteenmäki", "phosh-sig" ]

# Silverblue
[silverblue.x86_64]
fas = [ "siosm", "tpopela" ]
maintainers = [ "Timothée Ravier", "Tomáš Popela" ]
[silverblue.aarch64]
fas = [ "siosm", "tpopela" ]
maintainers = [ "Timothée Ravier", "Tomáš Popela" ]

# Kinoite
[kinoite.x86_64]
fas = [ "siosm" ]
maintainers = [ "Timothée Ravier" ]
[kinoite.aarch64]
fas = [ "siosm" ]
maintainers = [ "Timothée Ravier" ]

# Sway Atomic
[sericea.x86_64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]
[sericea.aarch64]
fas = [ "alebastr", "jkonecny", "anthr76", "fale" ]
maintainers = [ "Aleksei Bavshin", "Jiří Konečný", "Anthony Rabbito", "Fabio Alessandro Locati" ]

# Budgie Atomic
[onyx.x86_64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]
[onyx.aarch64]
fas = [ "joshstrobl" ]
maintainers = [ "Joshua Strobl" ]

# COSMIC Atomic
[cosmic-atomic.x86_64]
fas = [ "ryanabx" ]
maintainers = [ "Ryan Brue" ]
[cosmic-atomic.aarch64]
fas = [ "ryanabx" ]
maintainers = [ "Ryan Brue" ]
